# Project Milestone 4

In [21]:
import pandas as pd
import json
import requests

## Loading Dataset

In [22]:
# get summary of cases
response = requests.get('https://api.covid19api.com/summary')

In [23]:
# turn into json data
summary = response.json()

In [24]:
summary

{'ID': '66f989a7-bddf-466b-aa7b-782735411db5',
 'Message': '',
 'Global': {'NewConfirmed': 469555,
  'TotalConfirmed': 635333213,
  'NewDeaths': 2587,
  'TotalDeaths': 6611892,
  'NewRecovered': 0,
  'TotalRecovered': 0,
  'Date': '2022-11-19T04:48:24.726Z'},
 'Countries': [{'ID': '221da756-eeb5-471d-9ce0-a34402529685',
   'Country': 'Afghanistan',
   'CountryCode': 'AF',
   'Slug': 'afghanistan',
   'NewConfirmed': 162,
   'TotalConfirmed': 204982,
   'NewDeaths': 0,
   'TotalDeaths': 7830,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '2b42f779-b7d7-4d57-847d-0ebf54bec0d4',
   'Country': 'Albania',
   'CountryCode': 'AL',
   'Slug': 'albania',
   'NewConfirmed': 18,
   'TotalConfirmed': 333233,
   'NewDeaths': 0,
   'TotalDeaths': 3594,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'ad957377-7562-46b9-9ce7-a86ac838c2f2',
   'Country': 'Algeria',
   'CountryCode': 'DZ',
   'Slug': 'algeria',
   'NewConfirmed': 15,
   'TotalConfirmed': 270996,
   'NewDeaths': 0,
   'TotalDeaths': 6881,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '5d68d424-6d5b-4199-b4e0-e8ed3a3f1438',
   'Country': 'Andorra',
   'CountryCode': 'AD',
   'Slug': 'andorra',
   'NewConfirmed': 0,
   'TotalConfirmed': 46824,
   'NewDeaths': 0,
   'TotalDeaths': 156,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '5982eb80-efb2-499f-a22d-587f3b5a53b8',
   'Country': 'Angola',
   'CountryCode': 'AO',
   'Slug': 'angola',
   'NewConfirmed': 0,
   'TotalConfirmed': 103131,
   'NewDeaths': 0,
   'TotalDeaths': 1917,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '9b066a10-f36e-4813-8257-8ff1c0184cc6',
   'Country': 'Antarctica',
   'CountryCode': 'AQ',
   'Slug': 'antarctica',
   'NewConfirmed': 0,
   'TotalConfirmed': 11,
   'NewDeaths': 0,
   'TotalDeaths': 0,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '10ba6112-da91-4006-a520-358730a85e61',
   'Country': 'Antigua and Barbuda',
   'CountryCode': 'AG',
   'Slug': 'antigua-and-barbuda',
   'NewConfirmed': 0,
   'TotalConfirmed': 9106,
   'NewDeaths': 0,
   'TotalDeaths': 146,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '438a550d-1178-4038-890c-89300727700d',
   'Country': 'Argentina',
   'CountryCode': 'AR',
   'Slug': 'argentina',
   'NewConfirmed': 0,
   'TotalConfirmed': 9721718,
   'NewDeaths': 0,
   'TotalDeaths': 130011,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '74bfde73-cab0-4099-97b0-72b6c7b76ad2',
   'Country': 'Armenia',
   'CountryCode': 'AM',
   'Slug': 'armenia',
   'NewConfirmed': 0,
   'TotalConfirmed': 445513,
   'NewDeaths': 0,
   'TotalDeaths': 8709,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'b97932fe-cc00-42af-a8b7-485a483d5cdf',
   'Country': 'Australia',
   'CountryCode': 'AU',
   'Slug': 'australia',
   'NewConfirmed': 59318,
   'TotalConfirmed': 10553237,
   'NewDeaths': 77,
   'TotalDeaths': 15976,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'e0344b24-e2cf-4381-b182-95fc0761421a',
   'Country': 'Austria',
   'CountryCode': 'AT',
   'Slug': 'austria',
   'NewConfirmed': 4511,
   'TotalConfirmed': 5506697,
   'NewDeaths': 8,
   'TotalDeaths': 21124,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'bbe61b45-0890-4eda-b2e7-908ff5c9c80f',
   'Country': 'Azerbaijan',
   'CountryCode': 'AZ',
   'Slug': 'azerbaijan',
   'NewConfirmed': 44,
   'TotalConfirmed': 823849,
   'NewDeaths': 1,
   'TotalDeaths': 9968,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '8894afbe-a909-4e06-852c-d162467f551a',
   'Country': 'Bahamas',
   'CountryCode': 'BS',
   'Slug': 'bahamas',
   'NewConfirmed': 0,
   'TotalConfirmed': 37439,
   'NewDeaths': 0,
   'TotalDeaths': 833,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'b69df743-ede9-40a2-a805-e50bc9d47598',
   'Country': 'Bahrain',
   'CountryCode': 'BH',
   'Slug': 'bahrain',
   'NewConfirmed': 241,
   'TotalConfirmed': 694464,
   'NewDeaths': 0,
   'TotalDeaths': 1532,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'bee7e5fe-dca5-42ec-ab7d-4752b253f652',
   'Country': 'Bangladesh',
   'CountryCode': 'BD',
   'Slug': 'bangladesh',
   'NewConfirmed': 38,
   'TotalConfirmed': 2036306,
   'NewDeaths': 0,
   'TotalDeaths': 29430,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'fbe390f0-0086-4d25-aff9-7a1f34d04844',
   'Country': 'Barbados',
   'CountryCode': 'BB',
   'Slug': 'barbados',
   'NewConfirmed': 0,
   'TotalConfirmed': 103545,
   'NewDeaths': 0,
   'TotalDeaths': 564,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '237d3deb-f170-4e5c-9587-4f01e4fe75ba',
   'Country': 'Belarus',
   'CountryCode': 'BY',
   'Slug': 'belarus',
   'NewConfirmed': 0,
   'TotalConfirmed': 994037,
   'NewDeaths': 0,
   'TotalDeaths': 7118,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '337dd1f6-7ac0-41b8-b96e-450bbdc07604',
   'Country': 'Belgium',
   'CountryCode': 'BE',
   'Slug': 'belgium',
   'NewConfirmed': 2935,
   'TotalConfirmed': 4627186,
   'NewDeaths': 21,
   'TotalDeaths': 33021,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '142c121f-863f-48fd-a8a5-83e6ee22742c',
   'Country': 'Belize',
   'CountryCode': 'BZ',
   'Slug': 'belize',
   'NewConfirmed': 0,
   'TotalConfirmed': 68988,
   'NewDeaths': 0,
   'TotalDeaths': 687,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'ea344d12-6cee-4767-95af-7d5c48cc8960',
   'Country': 'Benin',
   'CountryCode': 'BJ',
   'Slug': 'benin',
   'NewConfirmed': 0,
   'TotalConfirmed': 27922,
   'NewDeaths': 0,
   'TotalDeaths': 163,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '0ed20c1d-7986-42d5-bc70-d10e522021ad',
   'Country': 'Bhutan',
   'CountryCode': 'BT',
   'Slug': 'bhutan',
   'NewConfirmed': 0,
   'TotalConfirmed': 62460,
   'NewDeaths': 0,
   'TotalDeaths': 21,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'da66ac72-6277-4ba4-9e70-cc0ab6adb96b',
   'Country': 'Bolivia',
   'CountryCode': 'BO',
   'Slug': 'bolivia',
   'NewConfirmed': 0,
   'TotalConfirmed': 1110014,
   'NewDeaths': 0,
   'TotalDeaths': 22244,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '64727a1b-246e-4fe1-a76d-71a314e8ddac',
   'Country': 'Bosnia and Herzegovina',
   'CountryCode': 'BA',
   'Slug': 'bosnia-and-herzegovina',
   'NewConfirmed': 21,
   'TotalConfirmed': 400322,
   'NewDeaths': 1,
   'TotalDeaths': 16190,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '62e802a1-c872-43af-8b15-6a62ecb72c64',
   'Country': 'Botswana',
   'CountryCode': 'BW',
   'Slug': 'botswana',
   'NewConfirmed': 0,
   'TotalConfirmed': 326344,
   'NewDeaths': 0,
   'TotalDeaths': 2790,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'a708be39-02ca-49fb-bd54-d75be4edea6d',
   'Country': 'Brazil',
   'CountryCode': 'BR',
   'Slug': 'brazil',
   'NewConfirmed': 32970,
   'TotalConfirmed': 34971043,
   'NewDeaths': 71,
   'TotalDeaths': 688835,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '9de38c05-4c58-42cb-a39b-d187c1aaf73f',
   'Country': 'Brunei Darussalam',
   'CountryCode': 'BN',
   'Slug': 'brunei',
   'NewConfirmed': 0,
   'TotalConfirmed': 248861,
   'NewDeaths': 0,
   'TotalDeaths': 225,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'd25cf873-c018-4959-b32d-e7592bc8acae',
   'Country': 'Bulgaria',
   'CountryCode': 'BG',
   'Slug': 'bulgaria',
   'NewConfirmed': 220,
   'TotalConfirmed': 1284838,
   'NewDeaths': 10,
   'TotalDeaths': 37988,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '3c965657-1ec8-4a8e-b435-efe657ae3dd0',
   'Country': 'Burkina Faso',
   'CountryCode': 'BF',
   'Slug': 'burkina-faso',
   'NewConfirmed': 0,
   'TotalConfirmed': 21631,
   'NewDeaths': 0,
   'TotalDeaths': 387,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'af439564-0703-4e54-bfc7-2244c586cce9',
   'Country': 'Burundi',
   'CountryCode': 'BI',
   'Slug': 'burundi',
   'NewConfirmed': 0,
   'TotalConfirmed': 50639,
   'NewDeaths': 0,
   'TotalDeaths': 38,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '9761ee02-2894-42db-90e4-968b9416b785',
   'Country': 'Cambodia',
   'CountryCode': 'KH',
   'Slug': 'cambodia',
   'NewConfirmed': 3,
   'TotalConfirmed': 138010,
   'NewDeaths': 0,
   'TotalDeaths': 3056,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '5d80cef9-14c7-4691-84a9-12b6d7b8d394',
   'Country': 'Cameroon',
   'CountryCode': 'CM',
   'Slug': 'cameroon',
   'NewConfirmed': 0,
   'TotalConfirmed': 123993,
   'NewDeaths': 0,
   'TotalDeaths': 1965,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '89c79753-c41e-465b-85e6-6b3393adc375',
   'Country': 'Canada',
   'CountryCode': 'CA',
   'Slug': 'canada',
   'NewConfirmed': 6001,
   'TotalConfirmed': 3800649,
   'NewDeaths': 144,
   'TotalDeaths': 42523,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '6146bdb8-aa7d-4049-a2dc-1deae209ff0d',
   'Country': 'Cape Verde',
   'CountryCode': 'CV',
   'Slug': 'cape-verde',
   'NewConfirmed': 18,
   'TotalConfirmed': 62758,
   'NewDeaths': 0,
   'TotalDeaths': 410,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'de2282dc-90b2-4601-80d9-b88532e3192f',
   'Country': 'Central African Republic',
   'CountryCode': 'CF',
   'Slug': 'central-african-republic',
   'NewConfirmed': 0,
   'TotalConfirmed': 15289,
   'NewDeaths': 0,
   'TotalDeaths': 113,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'd538a46b-ff89-4546-a745-8fd810b54a13',
   'Country': 'Chad',
   'CountryCode': 'TD',
   'Slug': 'chad',
   'NewConfirmed': 0,
   'TotalConfirmed': 7637,
   'NewDeaths': 0,
   'TotalDeaths': 194,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '30d12c96-b3dc-4124-b7b3-15b77016246a',
   'Country': 'Chile',
   'CountryCode': 'CL',
   'Slug': 'chile',
   'NewConfirmed': 6904,
   'TotalConfirmed': 4859241,
   'NewDeaths': 50,
   'TotalDeaths': 62102,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '8e9a671a-b624-40e3-a486-7585933beb54',
   'Country': 'China',
   'CountryCode': 'CN',
   'Slug': 'china',
   'NewConfirmed': 10324,
   'TotalConfirmed': 2295014,
   'NewDeaths': 12,
   'TotalDeaths': 15801,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'b43c567d-8d62-4abc-87b6-fd6f298c4fd3',
   'Country': 'Colombia',
   'CountryCode': 'CO',
   'Slug': 'colombia',
   'NewConfirmed': 1298,
   'TotalConfirmed': 6312657,
   'NewDeaths': 19,
   'TotalDeaths': 141881,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'e33ab9d8-c1e9-402d-ab14-10fa03f93fd6',
   'Country': 'Comoros',
   'CountryCode': 'KM',
   'Slug': 'comoros',
   'NewConfirmed': 0,
   'TotalConfirmed': 8925,
   'NewDeaths': 0,
   'TotalDeaths': 161,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '9c686ca5-5054-44b5-98ca-836e570e3655',
   'Country': 'Congo (Brazzaville)',
   'CountryCode': 'CG',
   'Slug': 'congo-brazzaville',
   'NewConfirmed': 301,
   'TotalConfirmed': 25375,
   'NewDeaths': 0,
   'TotalDeaths': 386,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '144baef3-395a-4665-88ef-8a69dfa219b8',
   'Country': 'Congo (Kinshasa)',
   'CountryCode': 'CD',
   'Slug': 'congo-kinshasa',
   'NewConfirmed': 0,
   'TotalConfirmed': 93467,
   'NewDeaths': 0,
   'TotalDeaths': 1447,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'ecf08bc1-2dd1-4587-89b3-40c78cf89953',
   'Country': 'Costa Rica',
   'CountryCode': 'CR',
   'Slug': 'costa-rica',
   'NewConfirmed': 0,
   'TotalConfirmed': 1140864,
   'NewDeaths': 0,
   'TotalDeaths': 9019,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '830d2130-feb3-48c9-8711-993124994a94',
   'Country': 'Croatia',
   'CountryCode': 'HR',
   'Slug': 'croatia',
   'NewConfirmed': 269,
   'TotalConfirmed': 1250968,
   'NewDeaths': 5,
   'TotalDeaths': 17249,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'cc11fe98-f420-49ba-9696-5981292d1112',
   'Country': 'Cuba',
   'CountryCode': 'CU',
   'Slug': 'cuba',
   'NewConfirmed': 1,
   'TotalConfirmed': 1111333,
   'NewDeaths': 0,
   'TotalDeaths': 8530,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '2a146402-0e4b-4d81-b71e-8ac765fbc6c3',
   'Country': 'Cyprus',
   'CountryCode': 'CY',
   'Slug': 'cyprus',
   'NewConfirmed': 0,
   'TotalConfirmed': 606287,
   'NewDeaths': 0,
   'TotalDeaths': 1210,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'cb3bbdbd-3a55-4584-9c21-2760df0ca7ca',
   'Country': 'Czech Republic',
   'CountryCode': 'CZ',
   'Slug': 'czech-republic',
   'NewConfirmed': 558,
   'TotalConfirmed': 4167299,
   'NewDeaths': 5,
   'TotalDeaths': 41743,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'af6056be-23bb-486f-b2e2-8a23a735eada',
   'Country': "Côte d'Ivoire",
   'CountryCode': 'CI',
   'Slug': 'cote-divoire',
   'NewConfirmed': 0,
   'TotalConfirmed': 87864,
   'NewDeaths': 0,
   'TotalDeaths': 829,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '6e821399-da22-4801-ba6e-275f8fde6709',
   'Country': 'Denmark',
   'CountryCode': 'DK',
   'Slug': 'denmark',
   'NewConfirmed': 574,
   'TotalConfirmed': 3391724,
   'NewDeaths': 1,
   'TotalDeaths': 7519,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '4077384f-26c1-4565-9170-334a33eed558',
   'Country': 'Djibouti',
   'CountryCode': 'DJ',
   'Slug': 'djibouti',
   'NewConfirmed': 0,
   'TotalConfirmed': 15690,
   'NewDeaths': 0,
   'TotalDeaths': 189,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '558c60ca-d206-4d00-969f-1994f696d244',
   'Country': 'Dominica',
   'CountryCode': 'DM',
   'Slug': 'dominica',
   'NewConfirmed': 0,
   'TotalConfirmed': 15760,
   'NewDeaths': 0,
   'TotalDeaths': 74,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'acaaf768-9ebe-4fc9-a5dd-b798c49164d4',
   'Country': 'Dominican Republic',
   'CountryCode': 'DO',
   'Slug': 'dominican-republic',
   'NewConfirmed': 0,
   'TotalConfirmed': 647868,
   'NewDeaths': 0,
   'TotalDeaths': 4384,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': 'b74e1e0a-288d-4e8b-9f6a-8bc75c7d6a23',
   'Country': 'Ecuador',
   'CountryCode': 'EC',
   'Slug': 'ecuador',
   'NewConfirmed': 0,
   'TotalConfirmed': 1009388,
   'NewDeaths': 0,
   'TotalDeaths': 35935,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '48c6986e-2fc5-4f3c-b2a2-8702849627b8',
   'Country': 'Egypt',
   'CountryCode': 'EG',
   'Slug': 'egypt',
   'NewConfirmed': 0,
   'TotalConfirmed': 515645,
   'NewDeaths': 0,
   'TotalDeaths': 24798,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '6323208e-fdda-45e0-a8f0-46e6abef8d91',
   'Country': 'El Salvador',
   'CountryCode': 'SV',
   'Slug': 'el-salvador',
   'NewConfirmed': 0,
   'TotalConfirmed': 201785,
   'NewDeaths': 0,
   'TotalDeaths': 4230,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '3a824f6d-ed47-4eab-8570-9396f04cfcce',
   'Country': 'Equatorial Guinea',
   'CountryCode': 'GQ',
   'Slug': 'equatorial-guinea',
   'NewConfirmed': 0,
   'TotalConfirmed': 17182,
   'NewDeaths': 0,
   'TotalDeaths': 183,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '05cc30db-b5cc-4b0a-8bbb-85b5043a4481',
   'Country': 'Eritrea',
   'CountryCode': 'ER',
   'Slug': 'eritrea',
   'NewConfirmed': 0,
   'TotalConfirmed': 10189,
   'NewDeaths': 0,
   'TotalDeaths': 103,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '13a02fc8-72db-4ff5-8f3c-af333c423d46',
   'Country': 'Estonia',
   'CountryCode': 'EE',
   'Slug': 'estonia',
   'NewConfirmed': 0,
   'TotalConfirmed': 608332,
   'NewDeaths': 0,
   'TotalDeaths': 2757,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '3d215b7e-9fd8-4ef2-97d8-994658f72162',
   'Country': 'Ethiopia',
   'CountryCode': 'ET',
   'Slug': 'ethiopia',
   'NewConfirmed': 30,
   'TotalConfirmed': 494270,
   'NewDeaths': 0,
   'TotalDeaths': 7572,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '03eb8807-c717-4df2-9f05-c5722b18a7ab',
   'Country': 'Fiji',
   'CountryCode': 'FJ',
   'Slug': 'fiji',
   'NewConfirmed': 20,
   'TotalConfirmed': 68307,
   'NewDeaths': 0,
   'TotalDeaths': 878,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '6f1b8301-b0bd-4ce8-8ecd-b77fb640f4c3',
   'Country': 'Finland',
   'CountryCode': 'FI',
   'Slug': 'finland',
   'NewConfirmed': 12003,
   'TotalConfirmed': 1384654,
   'NewDeaths': 260,
   'TotalDeaths': 7173,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},
  {'ID': '8d09c6c6-bd20-447a-8bdc-9501c767b70f',
   'Country': 'France',
   'CountryCode': 'FR',
   'Slug': 'france',
   'NewConfirmed': 33331,
   'TotalConfirmed': 37471008,
   'NewDeaths': 87,
   'TotalDeaths': 159129,
   'NewRecovered': 0,
   'TotalRecovered': 0,
   'Date': '2022-11-19T04:48:24.726Z',
   'Premium': {}},

In [25]:
# split data into global vs countries
summary_global = summary["Global"]
summary_countries = summary["Countries"]

In [26]:
cases_df = pd.json_normalize(summary_countries)
cases_df

,ID,Country,CountryCode,Slug,NewConfirmed,TotalConfirmed,NewDeaths,TotalDeaths,NewRecovered,TotalRecovered,Date
0,221da756-eeb5-471d-9ce0-a34402529685,Afghanistan,AF,afghanistan,162,204982,0,7830,0,0,2022-11-19T04:48:24.726Z
1,2b42f779-b7d7-4d57-847d-0ebf54bec0d4,Albania,AL,albania,18,333233,0,3594,0,0,2022-11-19T04:48:24.726Z
2,ad957377-7562-46b9-9ce7-a86ac838c2f2,Algeria,DZ,algeria,15,270996,0,6881,0,0,2022-11-19T04:48:24.726Z
3,5d68d424-6d5b-4199-b4e0-e8ed3a3f1438,Andorra,AD,andorra,0,46824,0,156,0,0,2022-11-19T04:48:24.726Z
4,5982eb80-efb2-499f-a22d-587f3b5a53b8,Angola,AO,angola,0,103131,0,1917,0,0,2022-11-19T04:48:24.726Z
...,...,...,...,...,...,...,...,...,...,...,...
192,ce90a13e-ea6a-4923-b7f4-be09df796e92,Venezuela (Bolivarian Republic),VE,venezuela,0,546534,0,5825,0,0,2022-11-19T04:48:24.726Z
193,d5597653-d1d2-4e10-99a0-e3510e5a5900,Viet Nam,VN,vietnam,509,11510484,0,43167,0,0,2022-11-19T04:48:24.726Z
194,ec6bf0e4-237e-415b-b065-fd232a9516f8,Yemen,YE,yemen,0,11945,0,2159,0,0,2022-11-19T04:48:24.726Z
195,fea122f6-5cfe-469d-ad8f-027f26992871,Zambia,ZM,zambia,0,333685,0,4017,0,0,2022-11-19T04:48:24.726Z
196,f6c30cfa-0e43-4697-a5c6-2be5e8d60f16,Zimbabwe,ZW,zimbabwe,0,257893,0,5606,0,0,2022-11-19T04:48:24.726Z

In [27]:
# normalize global cases
cases_global = pd.json_normalize(summary_global)

In [28]:
# add two back together for starting data set
cases_df = cases_global.append(cases_df)

## Transformation 1: Remove Unecessary Columns

The ID, Slug, and CountryCode columns are not necessary to our project so they will be removed.

In [29]:
# drop id, countrycode, slug columns
cases_df = cases_df.drop(["ID", "CountryCode", "Slug"], axis = 1)

In [30]:
cases_df

,NewConfirmed,TotalConfirmed,NewDeaths,TotalDeaths,NewRecovered,TotalRecovered,Date,Country
0,469555,635333213,2587,6611892,0,0,2022-11-19T04:48:24.726Z,NaN
0,162,204982,0,7830,0,0,2022-11-19T04:48:24.726Z,Afghanistan
1,18,333233,0,3594,0,0,2022-11-19T04:48:24.726Z,Albania
2,15,270996,0,6881,0,0,2022-11-19T04:48:24.726Z,Algeria
3,0,46824,0,156,0,0,2022-11-19T04:48:24.726Z,Andorra
...,...,...,...,...,...,...,...,...
192,0,546534,0,5825,0,0,2022-11-19T04:48:24.726Z,Venezuela (Bolivarian Republic)
193,509,11510484,0,43167,0,0,2022-11-19T04:48:24.726Z,Viet Nam
194,0,11945,0,2159,0,0,2022-11-19T04:48:24.726Z,Yemen
195,0,333685,0,4017,0,0,2022-11-19T04:48:24.726Z,Zambia
196,0,257893,0,5606,0,0,2022-11-19T04:48:24.726Z,Zimbabwe

## Transformation 2: Replace Headers

To keep the same convention we have in our other datasets, we will rename the columns to have underscores between words.

In [31]:
# rename columns
cases_df = cases_df.rename(columns={"NewConfirmed":"New_confirmed", "TotalConfirmed":"Total_confirmed", "NewDeaths":"New_deaths","TotalDeaths":"Total_deaths", "NewRecovered":"New_recovered", "TotalRecovered":"Total_recovered"})

In [32]:
cases_df

,New_confirmed,Total_confirmed,New_deaths,Total_deaths,New_recovered,Total_recovered,Date,Country
0,469555,635333213,2587,6611892,0,0,2022-11-19T04:48:24.726Z,NaN
0,162,204982,0,7830,0,0,2022-11-19T04:48:24.726Z,Afghanistan
1,18,333233,0,3594,0,0,2022-11-19T04:48:24.726Z,Albania
2,15,270996,0,6881,0,0,2022-11-19T04:48:24.726Z,Algeria
3,0,46824,0,156,0,0,2022-11-19T04:48:24.726Z,Andorra
...,...,...,...,...,...,...,...,...
192,0,546534,0,5825,0,0,2022-11-19T04:48:24.726Z,Venezuela (Bolivarian Republic)
193,509,11510484,0,43167,0,0,2022-11-19T04:48:24.726Z,Viet Nam
194,0,11945,0,2159,0,0,2022-11-19T04:48:24.726Z,Yemen
195,0,333685,0,4017,0,0,2022-11-19T04:48:24.726Z,Zambia
196,0,257893,0,5606,0,0,2022-11-19T04:48:24.726Z,Zimbabwe

## Transformation 3: Fix World Row

Because of how the data was formatted when pulled from the API, we had to attatch the world data separately from the rest, and now it isn't named as global in its column. We will fix that.

In [33]:
# fill na in country with World
cases_df["Country"].fillna("World", inplace=True)

In [34]:
cases_df

,New_confirmed,Total_confirmed,New_deaths,Total_deaths,New_recovered,Total_recovered,Date,Country
0,469555,635333213,2587,6611892,0,0,2022-11-19T04:48:24.726Z,World
0,162,204982,0,7830,0,0,2022-11-19T04:48:24.726Z,Afghanistan
1,18,333233,0,3594,0,0,2022-11-19T04:48:24.726Z,Albania
2,15,270996,0,6881,0,0,2022-11-19T04:48:24.726Z,Algeria
3,0,46824,0,156,0,0,2022-11-19T04:48:24.726Z,Andorra
...,...,...,...,...,...,...,...,...
192,0,546534,0,5825,0,0,2022-11-19T04:48:24.726Z,Venezuela (Bolivarian Republic)
193,509,11510484,0,43167,0,0,2022-11-19T04:48:24.726Z,Viet Nam
194,0,11945,0,2159,0,0,2022-11-19T04:48:24.726Z,Yemen
195,0,333685,0,4017,0,0,2022-11-19T04:48:24.726Z,Zambia
196,0,257893,0,5606,0,0,2022-11-19T04:48:24.726Z,Zimbabwe

## Transformation 4: Reset Index Rows

Concatenating the two data frames has caused the index to be off. So we will reset the index.

In [35]:
# reset index rows
cases_df.reset_index(inplace=True)

In [36]:
# drop reindex row
cases_df.drop("index", axis = 1, inplace=True)

In [37]:
cases_df

,New_confirmed,Total_confirmed,New_deaths,Total_deaths,New_recovered,Total_recovered,Date,Country
0,469555,635333213,2587,6611892,0,0,2022-11-19T04:48:24.726Z,World
1,162,204982,0,7830,0,0,2022-11-19T04:48:24.726Z,Afghanistan
2,18,333233,0,3594,0,0,2022-11-19T04:48:24.726Z,Albania
3,15,270996,0,6881,0,0,2022-11-19T04:48:24.726Z,Algeria
4,0,46824,0,156,0,0,2022-11-19T04:48:24.726Z,Andorra
...,...,...,...,...,...,...,...,...
193,0,546534,0,5825,0,0,2022-11-19T04:48:24.726Z,Venezuela (Bolivarian Republic)
194,509,11510484,0,43167,0,0,2022-11-19T04:48:24.726Z,Viet Nam
195,0,11945,0,2159,0,0,2022-11-19T04:48:24.726Z,Yemen
196,0,333685,0,4017,0,0,2022-11-19T04:48:24.726Z,Zambia
197,0,257893,0,5606,0,0,2022-11-19T04:48:24.726Z,Zimbabwe

## Transformation 5: Reorder the Columns

The data frame is not very readable with the country and date columns all to the left. To make it more readable, we will move those to the left and shift everything to the right.

In [38]:
# reorder rows
cases_df = cases_df.iloc[:,[6,7,0,1,2,3,4,5]]

In [39]:
cases_df

,Date,Country,New_confirmed,Total_confirmed,New_deaths,Total_deaths,New_recovered,Total_recovered
0,2022-11-19T04:48:24.726Z,World,469555,635333213,2587,6611892,0,0
1,2022-11-19T04:48:24.726Z,Afghanistan,162,204982,0,7830,0,0
2,2022-11-19T04:48:24.726Z,Albania,18,333233,0,3594,0,0
3,2022-11-19T04:48:24.726Z,Algeria,15,270996,0,6881,0,0
4,2022-11-19T04:48:24.726Z,Andorra,0,46824,0,156,0,0
...,...,...,...,...,...,...,...,...
193,2022-11-19T04:48:24.726Z,Venezuela (Bolivarian Republic),0,546534,0,5825,0,0
194,2022-11-19T04:48:24.726Z,Viet Nam,509,11510484,0,43167,0,0
195,2022-11-19T04:48:24.726Z,Yemen,0,11945,0,2159,0,0
196,2022-11-19T04:48:24.726Z,Zambia,0,333685,0,4017,0,0
197,2022-11-19T04:48:24.726Z,Zimbabwe,0,257893,0,5606,0,0

In [40]:
cases_df.to_csv(r'C:\Users\Stewart\Documents\GitHub\dsc540\cases_cleaned.csv', index=False)

## Ethical Implications of Data Wrangling

As with the previous milestone, this milestone's wrangling was mostly in regards to the readability of the dataset. While readability may not seem to be ethically motivated, it is clear that lack of readability can become unethical if the readability is done on purpose in order to mislead the reader. So while there may not be any direct implications from what has been done in the step, we have done oure best to make the dataset as clear and understandable as possible, so that any misunderstandings can be avoided.

With the dataset itself, however, we should definitely think about how accurate of a picture a snapshot of the pandemic can be. Total deaths and total confirmed can give a good idea of how badly a country has suffered but not necessarily how that suffering has aligned with changes in public health, which is one of the reasons we are using this dataset. As we move into the next step, we should see if possibly pulling in more data from throughout the past two years would provi